[package]
name = "chapter2-first-program"
version = "0.1.0"
authors = ["codec-abc <viot.camille@outlook.com>"]
edition = "2018"

[dependencies]
cv = { version = "0.6.0", path = "../../cv" }
rand = "0.8.4"
